export const POST_NBNS_BANNER_BEGIN = 'POST_NBNS_BANNER_BEGIN';
export const POST_NBNS_BANNER_SUCCESS = 'POST_NBNS_BANNER_SUCCESS';
export const POST_NBNS_BANNER_ERROR = 'POST_NBNS_BANNER_ERROR';

export const GET_NBNS_BANNER_BEGIN = 'GET_NBNS_BANNER_BEGIN';
export const GET_NBNS_BANNER_SUCCESS = 'GET_NBNS_BANNER_SUCCESS';
export const GET_NBNS_BANNER_ERROR = 'GET_NBNS_BANNER_ERROR';

export const UPDATE_NBNS_BANNER_BEGIN = 'UPDATE_NBNS_BANNER_BEGIN';
export const UPDATE_NBNS_BANNER_SUCCESS = 'UPDATE_NBNS_BANNER_SUCCESS';
export const UPDATE_NBNS_BANNER_ERROR = 'UPDATE_NBNS_BANNER_ERROR';

export const DELETE_NBNS_BANNER_BEGIN = 'DELETE_NBNS_BANNER_BEGIN';
export const DELETE_NBNS_BANNER_SUCCESS = 'DELETE_NBNS_BANNER_SUCCESS';
export const DELETE_NBNS_BANNER_ERROR = 'DELETE_NBNS_BANNER_ERROR';

export const UPDATE_NBNS_BANNER_STATUS_BEGIN = 'UPDATE_NBNS_BANNER_STATUS_BEGIN';
export const UPDATE_NBNS_BANNER_STATUS_SUCCESS = 'UPDATE_NBNS_BANNER_STATUS_SUCCESS';
export const UPDATE_NBNS_BANNER_STATUS_ERROR = 'UPDATE_NBNS_BANNER_STATUS_ERROR';
