export const FETCH_QUESTIONS_BEGIN = 'FETCH_QUESTIONS_BEGIN';
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_ERROR = 'FETCH_QUESTIONS_ERROR';

export const CREATE_QUESTION_BEGIN = 'CREATE_QUESTION_BEGIN';
export const CREATE_QUESTION_SUCCESS = 'CREATE_QUESTION_SUCCESS';
export const CREATE_QUESTION_ERROR = 'CREATE_QUESTION_ERROR';

export const UPDATE_QUESTION_BEGIN = 'UPDATE_QUESTION_BEGIN';
export const UPDATE_QUESTION_SUCCESS = 'UPDATE_QUESTION_SUCCESS';
export const UPDATE_QUESTION_ERROR = 'UPDATE_QUESTION_ERROR';

export const CHANGE_QUESTION_STATUS_BEGIN = 'CHANGE_QUESTION_STATUS_BEGIN';
export const CHANGE_QUESTION_STATUS_SUCCESS = 'CHANGE_QUESTION_STATUS_SUCCESS';
export const CHANGE_QUESTION_STATUS_ERROR = 'CHANGE_QUESTION_STATUS_ERROR';

export const DELETE_QUESTION_BEGIN = 'DELETE_QUESTION_BEGIN';
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS';
export const DELETE_QUESTION_ERROR = 'DELETE_QUESTION_ERROR';

// Front post questions -------->

export const POST_QUESTION_FRONT_BEGIN = 'POST_QUESTION_FRONT_BEGIN';
export const POST_QUESTION_FRONT_SUCCESS = 'POST_QUESTION_FRONT_SUCCESS';
export const POST_QUESTION_FRONT_ERROR = 'POST_QUESTION_FRONT_ERROR';

export const POST_QUESTION_CHECK_FRONT_BEGIN = 'POST_QUESTION_CHECK_FRONT_BEGIN';
export const POST_QUESTION_CHECK_FRONT_SUCCESS = 'POST_QUESTION_CHECK_FRONT_SUCCESS';
export const POST_QUESTION_CHECK_FRONT_ERROR = 'POST_QUESTION_CHECK_FRONT_ERROR';
