export const FETCH_QUESTIONS_BEGIN = 'FETCH_QUESTIONS_BEGIN';
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_ERROR = 'FETCH_QUESTIONS_ERROR';

export const CREATE_QUESTION_BEGIN = 'CREATE_QUESTION_BEGIN';
export const CREATE_QUESTION_SUCCESS = 'CREATE_QUESTION_SUCCESS';
export const CREATE_QUESTION_ERROR = 'CREATE_QUESTION_ERROR';

export const UPDATE_QUESTION_BEGIN = 'UPDATE_QUESTION_BEGIN';
export const UPDATE_QUESTION_SUCCESS = 'UPDATE_QUESTION_SUCCESS';
export const UPDATE_QUESTION_ERROR = 'UPDATE_QUESTION_ERROR';

export const CHANGE_QUESTION_STATUS_BEGIN = 'CHANGE_QUESTION_STATUS_BEGIN';
export const CHANGE_QUESTION_STATUS_SUCCESS = 'CHANGE_QUESTION_STATUS_SUCCESS';
export const CHANGE_QUESTION_STATUS_ERROR = 'CHANGE_QUESTION_STATUS_ERROR';

export const DELETE_QUESTION_BEGIN = 'DELETE_QUESTION_BEGIN';
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS';
export const DELETE_QUESTION_ERROR = 'DELETE_QUESTION_ERROR';

// Front post questions -------->

export const POST_QUESTION_FRONT_BEGIN = 'POST_QUESTION_FRONT_BEGIN';
export const POST_QUESTION_FRONT_SUCCESS = 'POST_QUESTION_FRONT_SUCCESS';
export const POST_QUESTION_FRONT_ERROR = 'POST_QUESTION_FRONT_ERROR';

export const POST_QUESTION_CHECK_FRONT_BEGIN = 'POST_QUESTION_CHECK_FRONT_BEGIN';
export const POST_QUESTION_CHECK_FRONT_SUCCESS = 'POST_QUESTION_CHECK_FRONT_SUCCESS';
export const POST_QUESTION_CHECK_FRONT_ERROR = 'POST_QUESTION_CHECK_FRONT_ERROR';

export const FETCH_SURVEY_RESULT_BEGIN = 'FETCH_SURVEY_RESULT_BEGIN';
export const FETCH_SURVEY_RESULT_SUCCESS = 'FETCH_SURVEY_RESULT_SUCCESS';
export const FETCH_SURVEY_RESULT_ERROR = 'FETCH_SURVEY_RESULT_ERROR';

export const FETCH_PARTICIPANT_BEGIN = 'FETCH_PARTICIPANT_BEGIN';
export const FETCH_PARTICIPANT_SUCCESS = 'FETCH_PARTICIPANT_SUCCESS';
export const FETCH_PARTICIPANT_ERROR = 'FETCH_PARTICIPANT_ERROR';

export const FETCH_PARTICIPANT_RESULT_BEGIN = 'FETCH_PARTICIPANT_RESULT_BEGIN';
export const FETCH_PARTICIPANT_RESULT_SUCCESS = 'FETCH_PARTICIPANT_RESULT_SUCCESS';
export const FETCH_PARTICIPANT_RESULT_ERROR = 'FETCH_PARTICIPANT_RESULT_ERROR';

// status----
export const FETCH_SURVEY_BEGIN = 'FETCH_SURVEY_BEGIN';
export const FETCH_SURVEY_SUCCESS = 'FETCH_SURVEY_SUCCESS';
export const FETCH_SURVEY_ERROR = 'FETCH_SURVEY_ERROR';

export const CREATE_SURVEY_BEGIN = 'CREATE_SURVEY_BEGIN';
export const CREATE_SURVEY_SUCCESS = 'CREATE_SURVEY_SUCCESS';
export const CREATE_SURVEY_ERROR = 'CREATE_SURVEY_ERROR';

export const UPDATE_SURVEY_BEGIN = 'UPDATE_SURVEY_BEGIN';
export const UPDATE_SURVEY_SUCCESS = 'UPDATE_SURVEY_SUCCESS';
export const UPDATE_SURVEY_ERROR = 'UPDATE_SURVEY_ERROR';

export const CHANGE_SURVEY_STATUS_BEGIN = 'CHANGE_SURVEY_STATUS_BEGIN';
export const CHANGE_SURVEY_STATUS_SUCCESS = 'CHANGE_SURVEY_STATUS_SUCCESS';
export const CHANGE_SURVEY_STATUS_ERROR = 'CHANGE_SURVEY_STATUS_ERROR';

export const DELETE_SURVEY_BEGIN = 'DELETE_SURVEY_BEGIN';
export const DELETE_SURVEY_SUCCESS = 'DELETE_SURVEY_SUCCESS';
export const DELETE_SURVEY_ERROR = 'DELETE_SURVEY_ERROR';
