export const FETCH_SITE_SETTING_BEGIN = 'FETCH_SITE_SETTING_BEGIN';
export const FETCH_SITE_SETTING_SUCCESS = 'FETCH_SITE_SETTING_SUCCESS';
export const FETCH_SITE_SETTING_ERROR = 'FETCH_SITE_SETTING_ERROR';

export const FETCH_NEWS_BEGIN = 'FETCH_NEWS_BEGIN';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_ERROR = 'FETCH_NEWS_ERROR';

export const FETCH_NEWS_CATEGORY_BEGIN = 'FETCH_NEWS_CATEGORY_BEGIN';
export const FETCH_NEWS_CATEGORY_SUCCESS = 'FETCH_NEWS_CATEGORY_SUCCESS';
export const FETCH_NEWS_CATEGORY_ERROR = 'FETCH_NEWS_CATEGORY_ERROR';

export const FETCH_SINGLE_NEWS_BEGIN = 'FETCH_SINGLE_NEWS_BEGIN';
export const FETCH_SINGLE_NEWS_SUCCESS = 'FETCH_SINGLE_NEWS_SUCCESS';
export const FETCH_SINGLE_NEWS_ERROR = 'FETCH_SINGLE_NEWS_ERROR';

export const FETCH_EVENTS_BEGIN = 'FETCH_EVENTS_BEGIN';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_ERROR = 'FETCH_EVENTS_ERROR';

export const FETCH_EVENTS_CATEGORY_BEGIN = 'FETCH_EVENTS_CATEGORY_BEGIN';
export const FETCH_EVENTS_CATEGORY_SUCCESS = 'FETCH_EVENTS_CATEGORY_SUCCESS';
export const FETCH_EVENTS_CATEGORY_ERROR = 'FETCH_EVENTS_CATEGORY_ERROR';

export const FETCH_SINGLE_EVENTS_BEGIN = 'FETCH_SINGLE_EVENTS_BEGIN';
export const FETCH_SINGLE_EVENTS_SUCCESS = 'FETCH_SINGLE_EVENTS_SUCCESS';
export const FETCH_SINGLE_EVENTS_ERROR = 'FETCH_SINGLE_EVENTS_ERROR';

export const POST_CONTACT_BEGIN = 'POST_CONTACT_BEGIN';
export const POST_CONTACT_SUCCESS = 'POST_CONTACT_SUCCESS';
export const POST_CONTACT_ERROR = 'POST_CONTACT_ERROR';

export const FETCH_CONTACT_BEGIN = 'FETCH_CONTACT_BEGIN';
export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS';
export const FETCH_CONTACT_ERROR = 'FETCH_CONTACT_ERROR';

export const FETCH_BANNER_BEGIN = 'FETCH_BANNER_BEGIN';
export const FETCH_BANNER_SUCCESS = 'FETCH_BANNER_SUCCESS';
export const FETCH_BANNER_ERROR = 'FETCH_BANNER_ERROR';

export const DELETE_CONTACT_BEGIN = 'DELETE_CONTACT_BEGIN';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_ERROR = 'DELETE_CONTACT_ERROR';

export const FETCH_OUR_TEAM_BEGIN = 'FETCH_OUR_TEAM_BEGIN';
export const FETCH_OUR_TEAM_SUCCESS = 'FETCH_OUR_TEAM_SUCCESS';
export const FETCH_OUR_TEAM_ERROR = 'FETCH_OUR_TEAM_ERROR';

export const FETCH_SINGLE_TEAMS_BEGIN = 'FETCH_SINGLE_TEAMS_BEGIN';
export const FETCH_SINGLE_TEAMS_SUCCESS = 'FETCH_SINGLE_TEAMS_SUCCESS';
export const FETCH_SINGLE_TEAMS_ERROR = 'FETCH_SINGLE_TEAMS_ERROR';

export const FETCH_NCC_BEGIN = 'FETCH_NCC_BEGIN';
export const FETCH_NCC_SUCCESS = 'FETCH_NCC_SUCCESS';
export const FETCH_NCC_ERROR = 'FETCH_NCC_ERROR';

export const FETCH_CANDIDATE_BEGIN = 'FETCH_CANDIDATE_BEGIN';
export const FETCH_CANDIDATE_SUCCESS = 'FETCH_CANDIDATE_SUCCESS';
export const FETCH_CANDIDATE_ERROR = 'FETCH_CANDIDATE_ERROR';

export const FETCH_NBNS_SETTING_BEGIN = 'FETCH_NBNS_SETTING_BEGIN';
export const FETCH_NBNS_SETTING_SUCCESS = 'FETCH_NBNS_SETTING_SUCCESS';
export const FETCH_NBNS_SETTING_ERROR = 'FETCH_NBNS_SETTING_ERROR';

export const FETCH_DEPARTMENT_BEGIN = 'FETCH_DEPARTMENT_BEGIN';
export const FETCH_DEPARTMENT_SUCCESS = 'FETCH_DEPARTMENT_SUCCESS';
export const FETCH_DEPARTMENT_ERROR = 'FETCH_DEPARTMENT_ERROR';

export const FETCH_CONTINENTS_BEGIN = 'FETCH_CONTINENTS_BEGIN';
export const FETCH_CONTINENTS_SUCCESS = 'FETCH_CONTINENTS_SUCCESS';
export const FETCH_CONTINENTS_ERROR = 'FETCH_CONTINENTS_ERROR';

export const FETCH_BUSINESS_BEGIN = 'FETCH_BUSINESS_BEGIN';
export const FETCH_BUSINESS_SUCCESS = 'FETCH_BUSINESS_SUCCESS';
export const FETCH_BUSINESS_ERROR = 'FETCH_BUSINESS_ERROR';

export const FETCH_SINGLE_BUSINESS_BEGIN = 'FETCH_SINGLE_BUSINESS_BEGIN';
export const FETCH_SINGLE_BUSINESS_SUCCESS = 'FETCH_SINGLE_BUSINESS_SUCCESS';
export const FETCH_SINGLE_BUSINESS_ERROR = 'FETCH_SINGLE_BUSINESS_ERROR';

export const POST_BUSINESS_CONTACT_BEGIN = 'POST_BUSINESS_CONTACT_BEGIN';
export const POST_BUSINESS_CONTACT_SUCCESS = 'POST_BUSINESS_CONTACT_SUCCESS';
export const POST_BUSINESS_CONTACT_ERROR = 'POST_BUSINESS_CONTACT_ERROR';

export const FETCH_BUSINESS_CATEGORY_BEGIN = 'FETCH_BUSINESS_CATEGORY_BEGIN';
export const FETCH_BUSINESS_CATEGORY_SUCCESS = 'FETCH_BUSINESS_CATEGORY_SUCCESS';
export const FETCH_BUSINESS_CATEGORY_ERROR = 'FETCH_BUSINESS_CATEGORY_ERROR';

export const FETCH_SINGLE_NCC_BEGIN = 'FETCH_SINGLE_NCC_BEGIN';
export const FETCH_SINGLE_NCC_SUCCESS = 'FETCH_SINGLE_NCC_SUCCESS';
export const FETCH_SINGLE_NCC_ERROR = 'FETCH_SINGLE_NCC_ERROR';

export const FETCH_SINGLE_USER_BEGIN = 'FETCH_SINGLE_USER_BEGIN';
export const FETCH_SINGLE_USER_SUCCESS = 'FETCH_SINGLE_USER_SUCCESS';
export const FETCH_SINGLE_USER_ERROR = 'FETCH_SINGLE_USER_ERROR';

export const POST_TEAMS_CONTACT_BEGIN = 'POST_TEAMS_CONTACT_BEGIN';
export const POST_TEAMS_CONTACT_SUCCESS = 'POST_TEAMS_CONTACT_SUCCESS';
export const POST_TEAMS_CONTACT_ERROR = 'POST_TEAMS_CONTACT_ERROR';

export const POST_ADVICE_BEGIN = 'POST_ADVICE_BEGIN';
export const POST_ADVICE_SUCCESS = 'POST_ADVICE_SUCCESS';
export const POST_ADVICE_ERROR = 'POST_ADVICE_ERROR';

export const FETCH_HOME_DATA_BEGIN = 'FETCH_HOME_DATA_BEGIN';
export const FETCH_HOME_DATA_SUCCESS = 'FETCH_HOME_DATA_SUCCESS';
export const FETCH_HOME_DATA_ERROR = 'FETCH_HOME_DATA_ERROR';

export const FETCH_SINGLE_HOME_DATA_BEGIN = 'FETCH_SINGLE_HOME_DATA_BEGIN';
export const FETCH_SINGLE_HOME_DATA_SUCCESS = 'FETCH_SINGLE_HOME_DATA_SUCCESS';
export const FETCH_SINGLE_HOME_DATA_ERROR = 'FETCH_SINGLE_HOME_DATA_ERROR';

export const FETCH_QUESTIONS_BEGIN = 'FETCH_QUESTIONS_BEGIN';
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_ERROR = 'FETCH_QUESTIONS_ERROR';

export const POST_EMAIL_CHECK_BEGIN = 'POST_EMAIL_CHECK_BEGIN';
export const POST_EMAIL_CHECK_SUCCESS = 'POST_EMAIL_CHECK_SUCCESS';
export const POST_EMAIL_CHECK_ERROR = 'POST_EMAIL_CHECK_ERROR';

export const STORE_DETAILS = 'STORE_DETAILS';

export const SET_ACTIVE_LINK = 'SET_ACTIVE_LINK';

export const FETCH_SURVEY_BEGIN = 'FETCH_SURVEY_BEGIN';
export const FETCH_SURVEY_SUCCESS = 'FETCH_SURVEY_SUCCESS';
export const FETCH_SURVEY_ERROR = 'FETCH_SURVEY_ERROR';

export const GET_COUNTRIES_LIST_CODE_BEGIN = 'GET_COUNTRIES_LIST_CODE_BEGIN';
export const GET_COUNTRIES_LIST_CODE_SUCCESS = 'GET_COUNTRIES_LIST_CODE_SUCCESS';
export const GET_COUNTRIES_LIST_CODE_ERROR = 'GET_COUNTRIES_LIST_CODE_ERROR';

export const POST_BUSINESS_JOIN_BEGIN = 'POST_BUSINESS_JOIN_BEGIN';
export const POST_BUSINESS_JOIN_SUCCESS = 'POST_BUSINESS_JOIN_SUCCESS';
export const POST_BUSINESS_JOIN_ERROR = 'POST_BUSINESS_JOIN_ERROR';

export const GET_BUSINESS_FOLLOW_BEGIN = 'GET_BUSINESS_FOLLOW_BEGIN';
export const GET_BUSINESS_FOLLOW_SUCCESS = 'GET_BUSINESS_FOLLOW_SUCCESS';
export const GET_BUSINESS_FOLLOW_ERROR = 'GET_BUSINESS_FOLLOW_ERROR';

export const DELETE_BUSINESS_FOLLOW_BEGIN = 'DELETE_BUSINESS_FOLLOW_BEGIN';
export const DELETE_BUSINESS_FOLLOW_SUCCESS = 'DELETE_BUSINESS_FOLLOW_SUCCESS';
export const DELETE_BUSINESS_FOLLOW_ERROR = 'DELETE_BUSINESS_FOLLOW_ERROR';

export const POST_NBNS_JOIN_BEGIN = 'POST_NBNS_JOIN_BEGIN';
export const POST_NBNS_JOIN_SUCCESS = 'POST_NBNS_JOIN_SUCCESS';
export const POST_NBNS_JOIN_ERROR = 'POST_NBNS_JOIN_ERROR';

export const GET_NBNS_FOLLOW_BEGIN = 'GET_NBNS_FOLLOW_BEGIN';
export const GET_NBNS_FOLLOW_SUCCESS = 'GET_NBNS_FOLLOW_SUCCESS';
export const GET_NBNS_FOLLOW_ERROR = 'GET_NBNS_FOLLOW_ERROR';

export const DELETE_NBNS_FOLLOW_BEGIN = 'DELETE_NBNS_FOLLOW_BEGIN';
export const DELETE_NBNS_FOLLOW_SUCCESS = 'DELETE_NBNS_FOLLOW_SUCCESS';
export const DELETE_NBNS_FOLLOW_ERROR = 'DELETE_NBNS_FOLLOW_ERROR';
