export const FETCH_SITE_SETTING_BEGIN = 'FETCH_SITE_SETTING_BEGIN';
export const FETCH_SITE_SETTING_SUCCESS = 'FETCH_SITE_SETTING_SUCCESS';
export const FETCH_SITE_SETTING_ERROR = 'FETCH_SITE_SETTING_ERROR';

export const FETCH_NEWS_BEGIN = 'FETCH_NEWS_BEGIN';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_ERROR = 'FETCH_NEWS_ERROR';

export const FETCH_SINGLE_NEWS_BEGIN = 'FETCH_SINGLE_NEWS_BEGIN';
export const FETCH_SINGLE_NEWS_SUCCESS = 'FETCH_SINGLE_NEWS_SUCCESS';
export const FETCH_SINGLE_NEWS_ERROR = 'FETCH_SINGLE_NEWS_ERROR';

export const FETCH_EVENTS_BEGIN = 'FETCH_EVENTS_BEGIN';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_ERROR = 'FETCH_EVENTS_ERROR';

export const FETCH_SINGLE_EVENTS_BEGIN = 'FETCH_SINGLE_EVENTS_BEGIN';
export const FETCH_SINGLE_EVENTS_SUCCESS = 'FETCH_SINGLE_EVENTS_SUCCESS';
export const FETCH_SINGLE_EVENTS_ERROR = 'FETCH_SINGLE_EVENTS_ERROR';

export const POST_CONTACT_BEGIN = 'POST_CONTACT_BEGIN';
export const POST_CONTACT_SUCCESS = 'POST_CONTACT_SUCCESS';
export const POST_CONTACT_ERROR = 'POST_CONTACT_ERROR';

export const FETCH_CONTACT_BEGIN = 'FETCH_CONTACT_BEGIN';
export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS';
export const FETCH_CONTACT_ERROR = 'FETCH_CONTACT_ERROR';
