export const FETCH_SITE_SETTING_BEGIN = 'FETCH_SITE_SETTING_BEGIN';
export const FETCH_SITE_SETTING_SUCCESS = 'FETCH_SITE_SETTING_SUCCESS';
export const FETCH_SITE_SETTING_ERROR = 'FETCH_SITE_SETTING_ERROR';

export const FETCH_NEWS_BEGIN = 'FETCH_NEWS_BEGIN';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_ERROR = 'FETCH_NEWS_ERROR';

export const FETCH_SINGLE_NEWS_BEGIN = 'FETCH_SINGLE_NEWS_BEGIN';
export const FETCH_SINGLE_NEWS_SUCCESS = 'FETCH_SINGLE_NEWS_SUCCESS';
export const FETCH_SINGLE_NEWS_ERROR = 'FETCH_SINGLE_NEWS_ERROR';

export const FETCH_EVENTS_BEGIN = 'FETCH_EVENTS_BEGIN';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_ERROR = 'FETCH_EVENTS_ERROR';

export const FETCH_SINGLE_EVENTS_BEGIN = 'FETCH_SINGLE_EVENTS_BEGIN';
export const FETCH_SINGLE_EVENTS_SUCCESS = 'FETCH_SINGLE_EVENTS_SUCCESS';
export const FETCH_SINGLE_EVENTS_ERROR = 'FETCH_SINGLE_EVENTS_ERROR';

export const POST_CONTACT_BEGIN = 'POST_CONTACT_BEGIN';
export const POST_CONTACT_SUCCESS = 'POST_CONTACT_SUCCESS';
export const POST_CONTACT_ERROR = 'POST_CONTACT_ERROR';

export const FETCH_CONTACT_BEGIN = 'FETCH_CONTACT_BEGIN';
export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS';
export const FETCH_CONTACT_ERROR = 'FETCH_CONTACT_ERROR';

export const FETCH_BANNER_BEGIN = 'FETCH_BANNER_BEGIN';
export const FETCH_BANNER_SUCCESS = 'FETCH_BANNER_SUCCESS';
export const FETCH_BANNER_ERROR = 'FETCH_BANNER_ERROR';

export const DELETE_CONTACT_BEGIN = 'DELETE_CONTACT_BEGIN';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_ERROR = 'DELETE_CONTACT_ERROR';

export const FETCH_OUR_TEAM_BEGIN = 'FETCH_OUR_TEAM_BEGIN';
export const FETCH_OUR_TEAM_SUCCESS = 'FETCH_OUR_TEAM_SUCCESS';
export const FETCH_OUR_TEAM_ERROR = 'FETCH_OUR_TEAM_ERROR';

export const FETCH_SINGLE_TEAMS_BEGIN = 'FETCH_SINGLE_TEAMS_BEGIN';
export const FETCH_SINGLE_TEAMS_SUCCESS = 'FETCH_SINGLE_TEAMS_SUCCESS';
export const FETCH_SINGLE_TEAMS_ERROR = 'FETCH_SINGLE_TEAMS_ERROR';

export const FETCH_NCC_BEGIN = 'FETCH_NCC_BEGIN';
export const FETCH_NCC_SUCCESS = 'FETCH_NCC_SUCCESS';
export const FETCH_NCC_ERROR = 'FETCH_NCC_ERROR';

export const FETCH_CANDIDATE_BEGIN = 'FETCH_CANDIDATE_BEGIN';
export const FETCH_CANDIDATE_SUCCESS = 'FETCH_CANDIDATE_SUCCESS';
export const FETCH_CANDIDATE_ERROR = 'FETCH_CANDIDATE_ERROR';

export const FETCH_NBNS_SETTING_BEGIN = 'FETCH_NBNS_SETTING_BEGIN';
export const FETCH_NBNS_SETTING_SUCCESS = 'FETCH_NBNS_SETTING_SUCCESS';
export const FETCH_NBNS_SETTING_ERROR = 'FETCH_NBNS_SETTING_ERROR';
