export const POST_NCC_BEGIN = 'POST_NCC_BEGIN';
export const POST_NCC_SUCCESS = 'POST_NCC_SUCCESS';
export const POST_NCC_ERROR = 'POST_NCC_ERROR';

export const GET_NCC_BEGIN = 'GET_NCC_BEGIN';
export const GET_NCC_SUCCESS = 'GET_NCC_SUCCESS';
export const GET_NCC_ERROR = 'GET_NCC_ERROR';

export const UPDATE_NCC_BEGIN = 'UPDATE_NCC_BEGIN';
export const UPDATE_NCC_SUCCESS = 'UPDATE_NCC_SUCCESS';
export const UPDATE_NCC_ERROR = 'UPDATE_NCC_ERROR';

export const DELETE_NCC_BEGIN = 'DELETE_NCC_BEGIN';
export const DELETE_NCC_SUCCESS = 'DELETE_NCC_SUCCESS';
export const DELETE_NCC_ERROR = 'DELETE_NCC_ERROR';

export const CHANGE_NCC_STATUS_BEGIN = 'CHANGE_NCC_STATUS_BEGIN';
export const CHANGE_NCC_STATUS_SUCCESS = 'CHANGE_NCC_STATUS_SUCCESS';
export const CHANGE_NCC_STATUS_ERROR = 'CHANGE_NCC_STATUS_ERROR';

export const GET_COUNTRIES_LIST_BEGIN = 'GET_COUNTRIES_LIST_BEGIN';
export const GET_COUNTRIES_LIST_SUCCESS = 'GET_COUNTRIES_LIST_SUCCESS';
export const GET_COUNTRIES_LIST_ERROR = 'GET_COUNTRIES_LIST_ERROR';
