export const POST_SITE_SETTINGS_BEGIN = 'POST_SITE_SETTINGS_BEGIN';
export const POST_SITE_SETTINGS_SUCCESS = 'POST_SITE_SETTINGS_SUCCESS';
export const POST_SITE_SETTINGS_ERROR = 'POST_SITE_SETTINGS_ERROR';

export const GET_SITE_SETTINGS_BEGIN = 'GET_SITE_SETTINGS_BEGIN';
export const GET_SITE_SETTINGS_SUCCESS = 'GET_SITE_SETTINGS_SUCCESS';
export const GET_SITE_SETTINGS_ERROR = 'GET_SITE_SETTINGS_ERROR';

export const POST_HOME_DATA_BEGIN = 'POST_HOME_DATA_BEGIN';
export const POST_HOME_DATA_SUCCESS = 'POST_HOME_DATA_SUCCESS';
export const POST_HOME_DATA_ERROR = 'POST_HOME_DATA_ERROR';

export const GET_HOME_DATA_BEGIN = 'GET_HOME_DATA_BEGIN';
export const GET_HOME_DATA_SUCCESS = 'GET_HOME_DATA_SUCCESS';
export const GET_HOME_DATA_ERROR = 'GET_HOME_DATA_ERROR';

export const UPDATE_HOME_DATA_BEGIN = 'UPDATE_HOME_DATA_BEGIN';
export const UPDATE_HOME_DATA_SUCCESS = 'UPDATE_HOME_DATA_SUCCESS';
export const UPDATE_HOME_DATA_ERROR = 'UPDATE_HOME_DATA_ERROR';

export const DELETE_HOME_DATA_BEGIN = 'DELETE_HOME_DATA_BEGIN';
export const DELETE_HOME_DATA_SUCCESS = 'DELETE_HOME_DATA_SUCCESS';
export const DELETE_HOME_DATA_ERROR = 'DELETE_HOME_DATA_ERROR';

export const UPDATE_HOME_DATA_STATUS_BEGIN = 'UPDATE_HOME_DATA_STATUS_BEGIN';
export const UPDATE_HOME_DATA_STATUS_SUCCESS = 'UPDATE_HOME_DATA_STATUS_SUCCESS';
export const UPDATE_HOME_DATA_STATUS_ERROR = 'UPDATE_HOME_DATA_STATUS_ERROR';

export const GET_NBNS_FOLLOWERS_BEGIN = 'GET_NBNS_FOLLOWERS_BEGIN';
export const GET_NBNS_FOLLOWERS_SUCCESS = 'GET_NBNS_FOLLOWERS_SUCCESS';
export const GET_NBNS_FOLLOWERS_ERROR = 'GET_NBNS_FOLLOWERS_ERROR';

export const POST_NBNS_USER_APPROVAL_BEGIN = 'POST_NBNS_USER_APPROVAL_BEGIN';
export const POST_NBNS_USER_APPROVAL_SUCCESS = 'POST_NBNS_USER_APPROVAL_SUCCESS';
export const POST_NBNS_USER_APPROVAL_ERROR = 'POST_NBNS_USER_APPROVAL_ERROR';
