export const POST_SITE_SETTINGS_BEGIN = 'POST_SITE_SETTINGS_BEGIN';
export const POST_SITE_SETTINGS_SUCCESS = 'POST_SITE_SETTINGS_SUCCESS';
export const POST_SITE_SETTINGS_ERROR = 'POST_SITE_SETTINGS_ERROR';

export const GET_SITE_SETTINGS_BEGIN = 'GET_SITE_SETTINGS_BEGIN';
export const GET_SITE_SETTINGS_SUCCESS = 'GET_SITE_SETTINGS_SUCCESS';
export const GET_SITE_SETTINGS_ERROR = 'GET_SITE_SETTINGS_ERROR';
