export const POST_GALLERY_BEGIN = 'POST_GALLERY_BEGIN';
export const POST_GALLERY_SUCCESS = 'POST_GALLERY_SUCCESS';
export const POST_GALLERY_ERROR = 'POST_GALLERY_ERROR';

export const GET_GALLERY_BEGIN = 'GET_GALLERY_BEGIN';
export const GET_GALLERY_SUCCESS = 'GET_GALLERY_SUCCESS';
export const GET_GALLERY_ERROR = 'GET_GALLERY_ERROR';

export const UPDATE_GALLERY_BEGIN = 'UPDATE_GALLERY_BEGIN';
export const UPDATE_GALLERY_SUCCESS = 'UPDATE_GALLERY_SUCCESS';
export const UPDATE_GALLERY_ERROR = 'UPDATE_GALLERY_ERROR';

export const DELETE_GALLERY_BEGIN = 'DELETE_GALLERY_BEGIN';
export const DELETE_GALLERY_SUCCESS = 'DELETE_GALLERY_SUCCESS';
export const DELETE_GALLERY_ERROR = 'DELETE_GALLERY_ERROR';

export const CHANGE_GALLERY_STATUS_BEGIN = 'CHANGE_GALLERY_STATUS_BEGIN';
export const CHANGE_GALLERY_STATUS_SUCCESS = 'CHANGE_GALLERY_STATUS_SUCCESS';
export const CHANGE_GALLERY_STATUS_ERROR = 'CHANGE_GALLERY_STATUS_ERROR';

export const POST_ARTICLE_BEGIN = 'POST_ARTICLE_BEGIN';
export const POST_ARTICLE_SUCCESS = 'POST_ARTICLE_SUCCESS';
export const POST_ARTICLE_ERROR = 'POST_ARTICLE_ERROR';

export const GET_ARTICLE_BEGIN = 'GET_ARTICLE_BEGIN';
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS';
export const GET_ARTICLE_ERROR = 'GET_ARTICLE_ERROR';

export const UPDATE_ARTICLE_BEGIN = 'UPDATE_ARTICLE_BEGIN';
export const UPDATE_ARTICLE_SUCCESS = 'UPDATE_ARTICLE_SUCCESS';
export const UPDATE_ARTICLE_ERROR = 'UPDATE_ARTICLE_ERROR';

export const DELETE_ARTICLE_BEGIN = 'DELETE_ARTICLE_BEGIN';
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_ERROR = 'DELETE_ARTICLE_ERROR';

export const CHANGE_ARTICLE_STATUS_BEGIN = 'CHANGE_ARTICLE_STATUS_BEGIN';
export const CHANGE_ARTICLE_STATUS_SUCCESS = 'CHANGE_ARTICLE_STATUS_SUCCESS';
export const CHANGE_ARTICLE_STATUS_ERROR = 'CHANGE_ARTICLE_STATUS_ERROR';

export const POST_PRESS_RELEASE_BEGIN = 'POST_PRESS_RELEASE_BEGIN';
export const POST_PRESS_RELEASE_SUCCESS = 'POST_PRESS_RELEASE_SUCCESS';
export const POST_PRESS_RELEASE_ERROR = 'POST_PRESS_RELEASE_ERROR';

export const GET_PRESS_RELEASE_BEGIN = 'GET_PRESS_RELEASE_BEGIN';
export const GET_PRESS_RELEASE_SUCCESS = 'GET_PRESS_RELEASE_SUCCESS';
export const GET_PRESS_RELEASE_ERROR = 'GET_PRESS_RELEASE_ERROR';

export const UPDATE_PRESS_RELEASE_BEGIN = 'UPDATE_PRESS_RELEASE_BEGIN';
export const UPDATE_PRESS_RELEASE_SUCCESS = 'UPDATE_PRESS_RELEASE_SUCCESS';
export const UPDATE_PRESS_RELEASE_ERROR = 'UPDATE_PRESS_RELEASE_ERROR';

export const DELETE_PRESS_RELEASE_BEGIN = 'DELETE_PRESS_RELEASE_BEGIN';
export const DELETE_PRESS_RELEASE_SUCCESS = 'DELETE_PRESS_RELEASE_SUCCESS';
export const DELETE_PRESS_RELEASE_ERROR = 'DELETE_PRESS_RELEASE_ERROR';

export const CHANGE_PRESS_RELEASE_STATUS_BEGIN = 'CHANGE_PRESS_RELEASE_STATUS_BEGIN';
export const CHANGE_PRESS_RELEASE_STATUS_SUCCESS = 'CHANGE_PRESS_RELEASE_STATUS_SUCCESS';
export const CHANGE_PRESS_RELEASE_STATUS_ERROR = 'CHANGE_PRESS_RELEASE_STATUS_ERROR';
