export const POST_DEPARTMENT_BEGIN = 'POST_DEPARTMENT_BEGIN';
export const POST_DEPARTMENT_SUCCESS = 'POST_DEPARTMENT_SUCCESS';
export const POST_DEPARTMENT_ERROR = 'POST_DEPARTMENT_ERROR';

export const GET_DEPARTMENT_BEGIN = 'GET_DEPARTMENT_BEGIN';
export const GET_DEPARTMENT_SUCCESS = 'GET_DEPARTMENT_SUCCESS';
export const GET_DEPARTMENT_ERROR = 'GET_DEPARTMENT_ERROR';

export const UPDATE_DEPARTMENT_BEGIN = 'UPDATE_DEPARTMENT_BEGIN';
export const UPDATE_DEPARTMENT_SUCCESS = 'UPDATE_DEPARTMENT_SUCCESS';
export const UPDATE_DEPARTMENT_ERROR = 'UPDATE_DEPARTMENT_ERROR';

export const DELETE_DEPARTMENT_BEGIN = 'DELETE_DEPARTMENT_BEGIN';
export const DELETE_DEPARTMENT_SUCCESS = 'DELETE_DEPARTMENT_SUCCESS';
export const DELETE_DEPARTMENT_ERROR = 'DELETE_DEPARTMENT_ERROR';

export const CHANGE_DEPARTMENT_STATUS_BEGIN = 'CHANGE_DEPARTMENT_STATUS_BEGIN';
export const CHANGE_DEPARTMENT_STATUS_SUCCESS = 'CHANGE_DEPARTMENT_STATUS_SUCCESS';
export const CHANGE_DEPARTMENT_STATUS_ERROR = 'CHANGE_DEPARTMENT_STATUS_ERROR';
