export const POST_DOWNLOAD_BEGIN = 'POST_DOWNLOAD_BEGIN';
export const POST_DOWNLOAD_SUCCESS = 'POST_DOWNLOAD_SUCCESS';
export const POST_DOWNLOAD_ERROR = 'POST_DOWNLOAD_ERROR';

export const GET_DOWNLOAD_BEGIN = 'GET_DOWNLOAD_BEGIN';
export const GET_DOWNLOAD_SUCCESS = 'GET_DOWNLOAD_SUCCESS';
export const GET_DOWNLOAD_ERROR = 'GET_DOWNLOAD_ERROR';

export const UPDATE_DOWNLOAD_BEGIN = 'UPDATE_DOWNLOAD_BEGIN';
export const UPDATE_DOWNLOAD_SUCCESS = 'UPDATE_DOWNLOAD_SUCCESS';
export const UPDATE_DOWNLOAD_ERROR = 'UPDATE_DOWNLOAD_ERROR';

export const DELETE_DOWNLOAD_BEGIN = 'DELETE_DOWNLOAD_BEGIN';
export const DELETE_DOWNLOAD_SUCCESS = 'DELETE_DOWNLOAD_SUCCESS';
export const DELETE_DOWNLOAD_ERROR = 'DELETE_DOWNLOAD_ERROR';

export const CHANGE_DOWNLOAD_STATUS_BEGIN = 'CHANGE_DOWNLOAD_STATUS_BEGIN';
export const CHANGE_DOWNLOAD_STATUS_SUCCESS = 'CHANGE_DOWNLOAD_STATUS_SUCCESS';
export const CHANGE_DOWNLOAD_STATUS_ERROR = 'CHANGE_DOWNLOAD_STATUS_ERROR';

export const SEARCH_DOWNLOAD = 'SEARCH_DOWNLOAD';
