export const POST_TEAMS_BEGIN = 'POST_TEAMS_BEGIN';
export const POST_TEAMS_SUCCESS = 'POST_TEAMS_SUCCESS';
export const POST_TEAMS_ERROR = 'POST_TEAMS_ERROR';

export const GET_TEAMS_BEGIN = 'GET_TEAMS_BEGIN';
export const GET_TEAMS_SUCCESS = 'GET_TEAMS_SUCCESS';
export const GET_TEAMS_ERROR = 'GET_TEAMS_ERROR';

export const UPDATE_TEAMS_BEGIN = 'UPDATE_TEAMS_BEGIN';
export const UPDATE_TEAMS_SUCCESS = 'UPDATE_TEAMS_SUCCESS';
export const UPDATE_TEAMS_ERROR = 'UPDATE_TEAMS_ERROR';

export const DELETE_TEAMS_BEGIN = 'DELETE_TEAMS_BEGIN';
export const DELETE_TEAMS_SUCCESS = 'DELETE_TEAMS_SUCCESS';
export const DELETE_TEAMS_ERROR = 'DELETE_TEAMS_ERROR';
