export const POST_NEWS_BEGIN = 'POST_NEWS_BEGIN';
export const POST_NEWS_SUCCESS = 'POST_NEWS_SUCCESS';
export const POST_NEWS_ERROR = 'POST_NEWS_ERROR';

export const GET_NEWS_BEGIN = 'GET_NEWS_BEGIN';
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';
export const GET_NEWS_ERROR = 'GET_NEWS_ERROR';

export const UPDATE_NEWS_BEGIN = 'UPDATE_NEWS_BEGIN';
export const UPDATE_NEWS_SUCCESS = 'UPDATE_NEWS_SUCCESS';
export const UPDATE_NEWS_ERROR = 'UPDATE_NEWS_ERROR';

export const DELETE_NEWS_BEGIN = 'DELETE_NEWS_BEGIN';
export const DELETE_NEWS_SUCCESS = 'DELETE_NEWS_SUCCESS';
export const DELETE_NEWS_ERROR = 'DELETE_NEWS_ERROR';

export const CHANGE_NEWS_STATUS_BEGIN = 'CHANGE_NEWS_STATUS_BEGIN';
export const CHANGE_NEWS_STATUS_SUCCESS = 'CHANGE_NEWS_STATUS_SUCCESS';
export const CHANGE_NEWS_STATUS_ERROR = 'CHANGE_NEWS_STATUS_ERROR';

export const POST_CATEGORY_BEGIN = 'POST_CATEGORY_BEGIN';
export const POST_CATEGORY_SUCCESS = 'POST_CATEGORY_SUCCESS';
export const POST_CATEGORY_ERROR = 'POST_CATEGORY_ERROR';

export const GET_CATEGORY_BEGIN = 'GET_CATEGORY_BEGIN';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_ERROR = 'GET_CATEGORY_ERROR';

export const UPDATE_CATEGORY_BEGIN = 'UPDATE_CATEGORY_BEGIN';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_ERROR = 'UPDATE_CATEGORY_ERROR';

export const DELETE_CATEGORY_BEGIN = 'DELETE_CATEGORY_BEGIN';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_ERROR = 'DELETE_CATEGORY_ERROR';

export const CHANGE_CATEGORY_STATUS_BEGIN = 'CHANGE_CATEGORY_STATUS_BEGIN';
export const CHANGE_CATEGORY_STATUS_SUCCESS = 'CHANGE_CATEGORY_STATUS_SUCCESS';
export const CHANGE_CATEGORY_STATUS_ERROR = 'CHANGE_CATEGORY_STATUS_ERROR';

export const POST_NEWS_ORDER_BEGIN = 'POST_NEWS_ORDER_BEGIN';
export const POST_NEWS_ORDER_SUCCESS = 'POST_NEWS_ORDER_SUCCESS';
export const POST_NEWS_ORDER_ERROR = 'POST_NEWS_ORDER_ERROR';

export const GET_NEWS_ORDER_BEGIN = 'GET_NEWS_ORDER_BEGIN';
export const GET_NEWS_ORDER_SUCCESS = 'GET_NEWS_ORDER_SUCCESS';
export const GET_NEWS_ORDER_ERROR = 'GET_NEWS_ORDER_ERROR';

export const DELETE_NEWS_ORDER_BEGIN = 'DELETE_NEWS_ORDER_BEGIN';
export const DELETE_NEWS_ORDER_SUCCESS = 'DELETE_NEWS_ORDER_SUCCESS';
export const DELETE_NEWS_ORDER_ERROR = 'DELETE_NEWS_ORDER_ERROR';
