export const POST_NEWS_BEGIN = 'POST_NEWS_BEGIN';
export const POST_NEWS_SUCCESS = 'POST_NEWS_SUCCESS';
export const POST_NEWS_ERROR = 'POST_NEWS_ERROR';

export const GET_NEWS_BEGIN = 'GET_NEWS_BEGIN';
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';
export const GET_NEWS_ERROR = 'GET_NEWS_ERROR';

export const UPDATE_NEWS_BEGIN = 'UPDATE_NEWS_BEGIN';
export const UPDATE_NEWS_SUCCESS = 'UPDATE_NEWS_SUCCESS';
export const UPDATE_NEWS_ERROR = 'UPDATE_NEWS_ERROR';

export const DELETE_NEWS_BEGIN = 'DELETE_NEWS_BEGIN';
export const DELETE_NEWS_SUCCESS = 'DELETE_NEWS_SUCCESS';
export const DELETE_NEWS_ERROR = 'DELETE_NEWS_ERROR';
