export const POST_EVENTS_BEGIN = 'POST_EVENTS_BEGIN';
export const POST_EVENTS_SUCCESS = 'POST_EVENTS_SUCCESS';
export const POST_EVENTS_ERROR = 'POST_EVENTS_ERROR';

export const GET_EVENTS_BEGIN = 'GET_EVENTS_BEGIN';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_ERROR = 'GET_EVENTS_ERROR';

export const UPDATE_EVENTS_BEGIN = 'UPDATE_EVENTS_BEGIN';
export const UPDATE_EVENTS_SUCCESS = 'UPDATE_EVENTS_SUCCESS';
export const UPDATE_EVENTS_ERROR = 'UPDATE_EVENTS_ERROR';

export const DELETE_EVENTS_BEGIN = 'DELETE_EVENTS_BEGIN';
export const DELETE_EVENTS_SUCCESS = 'DELETE_EVENTS_SUCCESS';
export const DELETE_EVENTS_ERROR = 'DELETE_EVENTS_ERROR';

export const CHANGE_EVENTS_STATUS_BEGIN = 'CHANGE_EVENTS_STATUS_BEGIN';
export const CHANGE_EVENTS_STATUS_SUCCESS = 'CHANGE_EVENTS_STATUS_SUCCESS';
export const CHANGE_EVENTS_STATUS_ERROR = 'CHANGE_EVENTS_STATUS_ERROR';

export const POST_CATEGORY_BEGIN = 'POST_CATEGORY_BEGIN';
export const POST_CATEGORY_SUCCESS = 'POST_CATEGORY_SUCCESS';
export const POST_CATEGORY_ERROR = 'POST_CATEGORY_ERROR';

export const GET_CATEGORY_BEGIN = 'GET_CATEGORY_BEGIN';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_ERROR = 'GET_CATEGORY_ERROR';

export const UPDATE_CATEGORY_BEGIN = 'UPDATE_CATEGORY_BEGIN';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_ERROR = 'UPDATE_CATEGORY_ERROR';

export const DELETE_CATEGORY_BEGIN = 'DELETE_CATEGORY_BEGIN';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_ERROR = 'DELETE_CATEGORY_ERROR';

export const CHANGE_CATEGORY_STATUS_BEGIN = 'CHANGE_CATEGORY_STATUS_BEGIN';
export const CHANGE_CATEGORY_STATUS_SUCCESS = 'CHANGE_CATEGORY_STATUS_SUCCESS';
export const CHANGE_CATEGORY_STATUS_ERROR = 'CHANGE_CATEGORY_STATUS_ERROR';
