export const POST_BANNER_BEGIN = 'POST_BANNER_BEGIN';
export const POST_BANNER_SUCCESS = 'POST_BANNER_SUCCESS';
export const POST_BANNER_ERROR = 'POST_BANNER_ERROR';

export const GET_BANNER_BEGIN = 'GET_BANNER_BEGIN';
export const GET_BANNER_SUCCESS = 'GET_BANNER_SUCCESS';
export const GET_BANNER_ERROR = 'GET_BANNER_ERROR';

export const UPDATE_BANNER_BEGIN = 'UPDATE_BANNER_BEGIN';
export const UPDATE_BANNER_SUCCESS = 'UPDATE_BANNER_SUCCESS';
export const UPDATE_BANNER_ERROR = 'UPDATE_BANNER_ERROR';

export const DELETE_BANNER_BEGIN = 'DELETE_BANNER_BEGIN';
export const DELETE_BANNER_SUCCESS = 'DELETE_BANNER_SUCCESS';
export const DELETE_BANNER_ERROR = 'DELETE_BANNER_ERROR';

export const UPDATE_BANNER_STATUS_BEGIN = 'UPDATE_BANNER_STATUS_BEGIN';
export const UPDATE_BANNER_STATUS_SUCCESS = 'UPDATE_BANNER_STATUS_SUCCESS';
export const UPDATE_BANNER_STATUS_ERROR = 'UPDATE_BANNER_STATUS_ERROR';
