export const FETCH_USERS_BEGIN = 'FETCH_USERS_BEGIN';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';

export const FETCH_USERS_DOWNLOAD_BEGIN = 'FETCH_USERS_DOWNLOAD_BEGIN';
export const FETCH_USERS_DOWNLOAD_SUCCESS = 'FETCH_USERS_DOWNLOAD_SUCCESS';
export const FETCH_USERS_DOWNLOAD_ERROR = 'FETCH_USERS_DOWNLOAD_ERROR';

export const CREATE_USER_BEGIN = 'CREATE_USER_BEGIN';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const APPROVE_USER_BEGIN = 'APPROVE_USER_BEGIN';
export const APPROVE_USER_SUCCESS = 'APPROVE_USER_SUCCESS';
export const APPROVE_USER_ERROR = 'APPROVE_USER_ERROR';

export const CHANGE_USER_STATUS_BEGIN = 'CHANGE_USER_STATUS_BEGIN';
export const CHANGE_USER_STATUS_SUCCESS = 'CHANGE_USER_STATUS_SUCCESS';
export const CHANGE_USER_STATUS_ERROR = 'CHANGE_USER_STATUS_ERROR';

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const CHANGE_USER_ROLE_BEGIN = 'CHANGE_USER_ROLE_BEGIN';
export const CHANGE_USER_ROLE_SUCCESS = 'CHANGE_USER_ROLE_SUCCESS';
export const CHANGE_USER_ROLE_ERROR = 'CHANGE_USER_ROLE_ERROR';

export const UPDATE_PROFILE_BEGIN = 'UPDATE_PROFILE_BEGIN';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

export const DELETE_USERS_BEGIN = 'DELETE_USERS_BEGIN';
export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS';
export const DELETE_USERS_ERROR = 'DELETE_USERS_ERROR';

export const SEARCH_USER = 'SEARCH_USER';
