export const POST_REGION_BEGIN = 'POST_REGION_BEGIN';
export const POST_REGION_SUCCESS = 'POST_REGION_SUCCESS';
export const POST_REGION_ERROR = 'POST_REGION_ERROR';

export const GET_REGION_BEGIN = 'GET_REGION_BEGIN';
export const GET_REGION_SUCCESS = 'GET_REGION_SUCCESS';
export const GET_REGION_ERROR = 'GET_REGION_ERROR';

export const UPDATE_REGION_BEGIN = 'UPDATE_REGION_BEGIN';
export const UPDATE_REGION_SUCCESS = 'UPDATE_REGION_SUCCESS';
export const UPDATE_REGION_ERROR = 'UPDATE_REGION_ERROR';

export const DELETE_REGION_BEGIN = 'DELETE_REGION_BEGIN';
export const DELETE_REGION_SUCCESS = 'DELETE_REGION_SUCCESS';
export const DELETE_REGION_ERROR = 'DELETE_REGION_ERROR';

export const UPDATE_REGION_STATUS_BEGIN = 'UPDATE_REGION_STATUS_BEGIN';
export const UPDATE_REGION_STATUS_SUCCESS = 'UPDATE_REGION_STATUS_SUCCESS';
export const UPDATE_REGION_STATUS_ERROR = 'UPDATE_REGION_STATUS_ERROR';
