export const GET_ADVICE_BEGIN = 'GET_ADVICE_BEGIN';
export const GET_ADVICE_SUCCESS = 'GET_ADVICE_SUCCESS';
export const GET_ADVICE_ERROR = 'GET_ADVICE_ERROR';

export const DELETE_ADVICE_BEGIN = 'DELETE_ADVICE_BEGIN';
export const DELETE_ADVICE_SUCCESS = 'DELETE_ADVICE_SUCCESS';
export const DELETE_ADVICE_ERROR = 'DELETE_ADVICE_ERROR';
