export const POST_EMAIL_TEMPLATE_BEGIN = 'POST_EMAIL_TEMPLATE_BEGIN';
export const POST_EMAIL_TEMPLATE_SUCCESS = 'POST_EMAIL_TEMPLATE_SUCCESS';
export const POST_EMAIL_TEMPLATE_ERROR = 'POST_EMAIL_TEMPLATE_ERROR';

export const GET_EMAIL_TEMPLATE_BEGIN = 'GET_EMAIL_TEMPLATE_BEGIN';
export const GET_EMAIL_TEMPLATE_SUCCESS = 'GET_EMAIL_TEMPLATE_SUCCESS';
export const GET_EMAIL_TEMPLATE_ERROR = 'GET_EMAIL_TEMPLATE_ERROR';

export const UPDATE_EMAIL_TEMPLATE_BEGIN = 'UPDATE_EMAIL_TEMPLATE_BEGIN';
export const UPDATE_EMAIL_TEMPLATE_SUCCESS = 'UPDATE_EMAIL_TEMPLATE_SUCCESS';
export const UPDATE_EMAIL_TEMPLATE_ERROR = 'UPDATE_EMAIL_TEMPLATE_ERROR';

export const DELETE_EMAIL_TEMPLATE_BEGIN = 'DELETE_EMAIL_TEMPLATE_BEGIN';
export const DELETE_EMAIL_TEMPLATE_SUCCESS = 'DELETE_EMAIL_TEMPLATE_SUCCESS';
export const DELETE_EMAIL_TEMPLATE_ERROR = 'DELETE_EMAIL_TEMPLATE_ERROR';

export const EMAIL_TEMPLATE_STATUS_SET_BEGIN = 'EMAIL_TEMPLATE_STATUS_SET_BEGIN';
export const EMAIL_TEMPLATE_STATUS_SET_SUCCESS = 'EMAIL_TEMPLATE_STATUS_SET_SUCCESS';
export const EMAIL_TEMPLATE_STATUS_SET_ERROR = 'EMAIL_TEMPLATE_STATUS_SET_ERROR';

export const EMAIL_TEMPLATE_STATUS_REMOVE_BEGIN = 'EMAIL_TEMPLATE_STATUS_REMOVE_BEGIN';
export const EMAIL_TEMPLATE_STATUS_REMOVE_SUCCESS = 'EMAIL_TEMPLATE_STATUS_REMOVE_SUCCESS';
export const EMAIL_TEMPLATE_STATUS_REMOVE_ERROR = 'EMAIL_TEMPLATE_STATUS_REMOVE_ERROR';
