export const POST_CANDIDATE_BEGIN = 'POST_CANDIDATE_BEGIN';
export const POST_CANDIDATE_SUCCESS = 'POST_CANDIDATE_SUCCESS';
export const POST_CANDIDATE_ERROR = 'POST_CANDIDATE_ERROR';

export const GET_CANDIDATE_BEGIN = 'GET_CANDIDATE_BEGIN';
export const GET_CANDIDATE_SUCCESS = 'GET_CANDIDATE_SUCCESS';
export const GET_CANDIDATE_ERROR = 'GET_CANDIDATE_ERROR';

export const UPDATE_CANDIDATE_BEGIN = 'UPDATE_CANDIDATE_BEGIN';
export const UPDATE_CANDIDATE_SUCCESS = 'UPDATE_CANDIDATE_SUCCESS';
export const UPDATE_CANDIDATE_ERROR = 'UPDATE_CANDIDATE_ERROR';

export const DELETE_CANDIDATE_BEGIN = 'DELETE_CANDIDATE_BEGIN';
export const DELETE_CANDIDATE_SUCCESS = 'DELETE_CANDIDATE_SUCCESS';
export const DELETE_CANDIDATE_ERROR = 'DELETE_CANDIDATE_ERROR';

export const CHANGE_CANDIDATE_STATUS_BEGIN = 'CHANGE_CANDIDATE_STATUS_BEGIN';
export const CHANGE_CANDIDATE_STATUS_SUCCESS = 'CHANGE_CANDIDATE_STATUS_SUCCESS';
export const CHANGE_CANDIDATE_STATUS_ERROR = 'CHANGE_CANDIDATE_STATUS_ERROR';
