export const POST_CATEGORY_BEGIN = 'POST_CATEGORY_BEGIN';
export const POST_CATEGORY_SUCCESS = 'POST_CATEGORY_SUCCESS';
export const POST_CATEGORY_ERROR = 'POST_CATEGORY_ERROR';

export const GET_CATEGORY_BEGIN = 'GET_CATEGORY_BEGIN';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_ERROR = 'GET_CATEGORY_ERROR';

export const UPDATE_CATEGORY_BEGIN = 'UPDATE_CATEGORY_BEGIN';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_ERROR = 'UPDATE_CATEGORY_ERROR';

export const DELETE_CATEGORY_BEGIN = 'DELETE_CATEGORY_BEGIN';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_ERROR = 'DELETE_CATEGORY_ERROR';

export const CHANGE_CATEGORY_STATUS_BEGIN = 'CHANGE_CATEGORY_STATUS_BEGIN';
export const CHANGE_CATEGORY_STATUS_SUCCESS = 'CHANGE_CATEGORY_STATUS_SUCCESS';
export const CHANGE_CATEGORY_STATUS_ERROR = 'CHANGE_CATEGORY_STATUS_ERROR';

export const POST_BUSINESS_BEGIN = 'POST_BUSINESS_BEGIN';
export const POST_BUSINESS_SUCCESS = 'POST_BUSINESS_SUCCESS';
export const POST_BUSINESS_ERROR = 'POST_BUSINESS_ERROR';

export const GET_BUSINESS_BEGIN = 'GET_BUSINESS_BEGIN';
export const GET_BUSINESS_SUCCESS = 'GET_BUSINESS_SUCCESS';
export const GET_BUSINESS_ERROR = 'GET_BUSINESS_ERROR';

export const UPDATE_BUSINESS_BEGIN = 'UPDATE_BUSINESS_BEGIN';
export const UPDATE_BUSINESS_SUCCESS = 'UPDATE_BUSINESS_SUCCESS';
export const UPDATE_BUSINESS_ERROR = 'UPDATE_BUSINESS_ERROR';

export const DELETE_BUSINESS_BEGIN = 'DELETE_BUSINESS_BEGIN';
export const DELETE_BUSINESS_SUCCESS = 'DELETE_BUSINESS_SUCCESS';
export const DELETE_BUSINESS_ERROR = 'DELETE_BUSINESS_ERROR';

export const CHANGE_BUSINESS_STATUS_BEGIN = 'CHANGE_BUSINESS_STATUS_BEGIN';
export const CHANGE_BUSINESS_STATUS_SUCCESS = 'CHANGE_BUSINESS_STATUS_SUCCESS';
export const CHANGE_BUSINESS_STATUS_ERROR = 'CHANGE_BUSINESS_STATUS_ERROR';

export const GET_CONTACT_BEGIN = 'GET_CONTACT_BEGIN';
export const GET_CONTACT_SUCCESS = 'GET_CONTACT_SUCCESS';
export const GET_CONTACT_ERROR = 'GET_CONTACT_ERROR';

export const DELETE_BUSINESS_CONTACT_BEGIN = 'DELETE_BUSINESS_CONTACT_BEGIN';
export const DELETE_BUSINESS_CONTACT_SUCCESS = 'DELETE_BUSINESS_CONTACT_SUCCESS';
export const DELETE_BUSINESS_CONTACT_ERROR = 'DELETE_BUSINESS_CONTACT_ERROR';

export const POST_BUSINESS_SERVICE_BEGIN = 'POST_BUSINESS_SERVICE_BEGIN';
export const POST_BUSINESS_SERVICE_SUCCESS = 'POST_BUSINESS_SERVICE_SUCCESS';
export const POST_BUSINESS_SERVICE_ERROR = 'POST_BUSINESS_SERVICE_ERROR';
